name: Ceedling Test and Code Coverage

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Install Ceedling
        run: gem install ceedling

      - name: Run Tests and Generate JUnit Report
        run: |
          ceedling test:all

      - name: Run Code coverage generator
        continue-on-error: true
        run: |
          sudo apt install gcovr
          ceedling gcov:all utils:gcov

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          detailed_summary: true
          include_passed: true
          report_paths: "build/artifacts/test/report_junit.xml"

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/artifacts/gcov/GcovCoverageCobertura.xml
          badge: true
          format: "markdown"
          output: "both"
      - name: Write coverage to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
